"""
src/ssp/docx_export.py

Exports SSP generation results to a professional Word document.
Uses python-docx (already in the venv).

The output format follows CMMC SSP conventions:
  - Cover page with org info
  - Table of contents placeholder
  - Per-family sections with control narratives
  - Evidence reference tables
  - Gap summary appendix
"""

import os
import datetime
from typing import Optional
from collections import defaultdict

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT


# NIST 800-171 family ordering and full names
FAMILY_ORDER = [
    ("AC", "Access Control"),
    ("AT", "Awareness and Training"),
    ("AU", "Audit and Accountability"),
    ("CM", "Configuration Management"),
    ("IA", "Identification and Authentication"),
    ("IR", "Incident Response"),
    ("MA", "Maintenance"),
    ("MP", "Media Protection"),
    ("PE", "Physical Protection"),
    ("PS", "Personnel Security"),
    ("RA", "Risk Assessment"),
    ("CA", "Security Assessment"),
    ("SC", "System and Communications Protection"),
    ("SI", "System and Information Integrity"),
]

FAMILY_LOOKUP = {abbrev: name for abbrev, name in FAMILY_ORDER}


def _add_cover_page(doc: Document, org_profile: dict):
    """Add a professional cover page."""
    # Spacer
    for _ in range(6):
        doc.add_paragraph("")

    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("SYSTEM SECURITY PLAN")
    run.font.size = Pt(28)
    run.font.color.rgb = RGBColor(0x1F, 0x3A, 0x5F)  # Navy blue
    run.bold = True

    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("NIST SP 800-171 Rev. 2 Compliance")
    run.font.size = Pt(16)
    run.font.color.rgb = RGBColor(0x4A, 0x4A, 0x4A)

    doc.add_paragraph("")

    # Org info
    info_lines = [
        ("Organization:", org_profile.get("org_name", "Organization")),
        ("System Name:", org_profile.get("system_name", "Information System")),
        ("Employees:", str(org_profile.get("employee_count", ""))),
        ("Facility:", org_profile.get("facility_type", "")),
        ("Document Date:", datetime.datetime.now().strftime("%B %d, %Y")),
        ("Classification:", "CUI // SP-SSP"),
        ("Version:", "1.0 — AI-Generated Draft"),
    ]

    for label, value in info_lines:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run_label = p.add_run(label + " ")
        run_label.bold = True
        run_label.font.size = Pt(11)
        run_value = p.add_run(value)
        run_value.font.size = Pt(11)

    # Disclaimer
    doc.add_paragraph("")
    disc = doc.add_paragraph()
    disc.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = disc.add_run(
        "NOTICE: This document was generated by AI and requires human review. "
        "All implementation narratives must be verified by the organization's "
        "Information System Security Officer (ISSO) before submission to a C3PAO."
    )
    run.font.size = Pt(9)
    run.italic = True
    run.font.color.rgb = RGBColor(0x88, 0x00, 0x00)

    doc.add_page_break()


def _add_toc_placeholder(doc: Document):
    """Add a table of contents placeholder section."""
    doc.add_heading("Table of Contents", level=1)
    p = doc.add_paragraph(
        "Update this Table of Contents by right-clicking and selecting "
        '"Update Field" after reviewing the document in Microsoft Word.'
    )
    p.italic = True
    doc.add_page_break()


def _add_system_description(doc: Document, org_profile: dict):
    """Add system description section."""
    doc.add_heading("1. System Description", level=1)

    doc.add_heading("1.1 System Overview", level=2)
    doc.add_paragraph(
        org_profile.get("system_description", "No system description provided.")
    )

    doc.add_heading("1.2 Tools and Technologies", level=2)
    tools = org_profile.get("tools_description", "Not specified")
    for line in tools.split("\n"):
        line = line.strip().lstrip("- ")
        if line:
            doc.add_paragraph(line, style="List Bullet")

    doc.add_heading("1.3 Network Environment", level=2)
    doc.add_paragraph(
        org_profile.get("network_description", "Not specified")
    )

    doc.add_page_break()


def _status_color(status: str) -> RGBColor:
    """Return color based on implementation status."""
    s = status.lower()
    if s == "implemented":
        return RGBColor(0x00, 0x70, 0x00)  # Green
    elif s == "partially implemented":
        return RGBColor(0xCC, 0x7A, 0x00)  # Orange
    elif s == "planned":
        return RGBColor(0x00, 0x55, 0xAA)  # Blue
    else:
        return RGBColor(0xCC, 0x00, 0x00)  # Red


def _add_control_section(doc: Document, result, control_number: int):
    """Add a single control's narrative to the document."""
    from src.agents.ssp_generator_v2 import SSPControlResult

    # Control heading
    heading_text = f"{result.control_id}"
    doc.add_heading(heading_text, level=3)

    # Status badge
    status_p = doc.add_paragraph()
    run = status_p.add_run(f"Implementation Status: {result.status}")
    run.bold = True
    run.font.color.rgb = _status_color(result.status)
    run.font.size = Pt(10)

    if result.error:
        err_p = doc.add_paragraph()
        run = err_p.add_run(f"ERROR: {result.error}")
        run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
        run.italic = True
        return

    # Narrative
    if result.narrative:
        doc.add_paragraph(result.narrative)

    # Evidence table — prefer real DB-linked artifacts over LLM-parsed refs
    db_artifacts = getattr(result, "db_artifact_refs", [])
    has_evidence = db_artifacts or result.evidence_artifacts

    if has_evidence:
        doc.add_paragraph("")
        ev_heading = doc.add_paragraph()
        run = ev_heading.add_run("Evidence Artifacts:")
        run.bold = True
        run.font.size = Pt(10)

        if db_artifacts:
            # Rich table from real DB records
            table = doc.add_table(rows=1, cols=4)
            table.style = "Light Grid Accent 1"
            table.alignment = WD_TABLE_ALIGNMENT.LEFT

            hdr = table.rows[0].cells
            hdr[0].text = "Artifact ID"
            hdr[1].text = "Filename"
            hdr[2].text = "Type"
            hdr[3].text = "SHA-256 (first 16)"

            for art in db_artifacts:
                row_cells = table.add_row().cells
                row_cells[0].text = art.get("id", "")
                row_cells[1].text = art.get("filename", "")
                row_cells[2].text = (
                    art.get("evidence_type")
                    or art.get("source_system")
                    or "N/A"
                )
                hash_val = art.get("sha256_hash", "")
                row_cells[3].text = (hash_val[:16] + "...") if hash_val else "pending"
        else:
            # Fallback: LLM-parsed artifact strings
            table = doc.add_table(rows=1, cols=2)
            table.style = "Light Grid Accent 1"
            table.alignment = WD_TABLE_ALIGNMENT.LEFT

            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = "Artifact ID"
            hdr_cells[1].text = "Description"

            for artifact in result.evidence_artifacts:
                row_cells = table.add_row().cells
                if artifact.startswith("["):
                    bracket_end = artifact.find("]")
                    if bracket_end > 0:
                        row_cells[0].text = artifact[1:bracket_end]
                        row_cells[1].text = artifact[bracket_end + 1:].strip()
                    else:
                        row_cells[0].text = ""
                        row_cells[1].text = artifact
                else:
                    row_cells[0].text = ""
                    row_cells[1].text = artifact

    # Gaps
    if result.gaps:
        doc.add_paragraph("")
        gap_heading = doc.add_paragraph()
        run = gap_heading.add_run("Gaps & Recommendations:")
        run.bold = True
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)

        for gap in result.gaps:
            doc.add_paragraph(gap, style="List Bullet")


def _add_gap_summary_appendix(doc: Document, results: list):
    """Add an appendix with all gaps consolidated."""
    doc.add_page_break()
    doc.add_heading("Appendix A: Gap Summary", level=1)

    gaps_by_family = defaultdict(list)
    for r in results:
        if r.gaps:
            # Extract family from control_id (e.g., "AC" from "AC.L2-3.1.1")
            family = r.control_id.split(".")[0]
            for gap in r.gaps:
                gaps_by_family[family].append((r.control_id, gap))

    if not gaps_by_family:
        doc.add_paragraph("No gaps identified across all controls.")
        return

    total_gaps = sum(len(g) for g in gaps_by_family.values())
    doc.add_paragraph(f"Total gaps identified: {total_gaps}")

    table = doc.add_table(rows=1, cols=3)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = "Family"
    hdr[1].text = "Control"
    hdr[2].text = "Gap Description"

    for family_abbrev in [f[0] for f in FAMILY_ORDER]:
        if family_abbrev in gaps_by_family:
            for control_id, gap in gaps_by_family[family_abbrev]:
                row = table.add_row().cells
                row[0].text = family_abbrev
                row[1].text = control_id
                row[2].text = gap


def _add_statistics_section(doc: Document, results: list):
    """Add generation statistics."""
    doc.add_page_break()
    doc.add_heading("Appendix B: Generation Statistics", level=1)

    total = len(results)
    statuses = defaultdict(int)
    for r in results:
        statuses[r.status] += 1
    errors = sum(1 for r in results if r.error)
    total_time = sum(r.generation_time_sec for r in results)
    gaps_count = sum(len(r.gaps) for r in results)

    stats = [
        ("Total controls processed", str(total)),
        ("Implemented", str(statuses.get("Implemented", 0))),
        ("Partially Implemented", str(statuses.get("Partially Implemented", 0))),
        ("Not Implemented", str(statuses.get("Not Implemented", 0))),
        ("Planned", str(statuses.get("Planned", 0))),
        ("Errors", str(errors)),
        ("Total gaps identified", str(gaps_count)),
        ("Total generation time", f"{total_time:.0f} seconds ({total_time / 60:.1f} minutes)"),
        ("Average per control", f"{total_time / max(total, 1):.1f} seconds"),
        ("Generated on", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")),
    ]

    table = doc.add_table(rows=len(stats), cols=2)
    table.style = "Light Grid Accent 1"
    for i, (label, value) in enumerate(stats):
        table.rows[i].cells[0].text = label
        table.rows[i].cells[1].text = value


def export_ssp_to_docx(
    results: list,
    org_profile: dict,
    output_path: str,
) -> str:
    """Export SSP generation results to a Word document.

    Args:
        results: List of SSPControlResult objects.
        org_profile: Organization profile dict.
        output_path: Full path for the output .docx file.

    Returns:
        The output path.
    """
    doc = Document()

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # Cover page
    _add_cover_page(doc, org_profile)

    # TOC placeholder
    _add_toc_placeholder(doc)

    # System description
    _add_system_description(doc, org_profile)

    # Group results by family
    results_by_family = defaultdict(list)
    for r in results:
        family_abbrev = r.control_id.split(".")[0]
        results_by_family[family_abbrev].append(r)

    # Section 2: Security Control Implementation
    doc.add_heading("2. Security Control Implementation", level=1)
    doc.add_paragraph(
        f"This section documents the implementation status of all {len(results)} "
        f"NIST SP 800-171 Rev. 2 security requirements for "
        f"{org_profile.get('org_name', 'the organization')}."
    )

    section_num = 1
    for family_abbrev, family_name in FAMILY_ORDER:
        family_results = results_by_family.get(family_abbrev, [])
        if not family_results:
            continue

        # Family heading
        doc.add_heading(f"2.{section_num} {family_name} ({family_abbrev})", level=2)

        # Family summary
        impl = sum(1 for r in family_results if r.status == "Implemented")
        partial = sum(1 for r in family_results if r.status == "Partially Implemented")
        not_impl = sum(1 for r in family_results if r.status in ("Not Implemented", "Planned") or r.error)
        doc.add_paragraph(
            f"Controls in family: {len(family_results)} | "
            f"Implemented: {impl} | Partial: {partial} | Not Implemented/Planned: {not_impl}"
        )

        # Sort controls within family
        family_results.sort(key=lambda r: r.control_id)

        for j, result in enumerate(family_results, 1):
            _add_control_section(doc, result, j)

        section_num += 1

    # Appendices
    _add_gap_summary_appendix(doc, results)
    _add_statistics_section(doc, results)

    # Save
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    doc.save(output_path)

    return output_path
