"""
src/documents/docx_builder.py
Builds professional Word documents from generated document sections.
Uses python-docx (already in venv).
"""

import os
from io import BytesIO
from datetime import datetime
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE


def build_docx(
    title: str,
    company_name: str,
    sections: list[dict],
    output_dir: str = "data/exports",
    doc_type: str = "document",
) -> tuple[str, bytes]:
    """
    Build a professional DOCX from generated sections.

    Writes the file to ``output_dir`` (local-dev convenience) AND returns
    the raw bytes so callers can persist them in the DB — required on
    Render where the filesystem is ephemeral.

    Returns:
        (filepath, file_bytes)
    """
    doc = Document()

    # --- Styles ---
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    # Heading styles
    for level, size, color in [(1, 16, "1B3A5C"), (2, 14, "2C5F8A"), (3, 12, "3D7AB5")]:
        heading_style = doc.styles[f"Heading {level}"]
        heading_style.font.name = "Calibri"
        heading_style.font.size = Pt(size)
        heading_style.font.bold = True
        heading_style.font.color.rgb = RGBColor(
            int(color[:2], 16), int(color[2:4], 16), int(color[4:], 16)
        )

    # --- Cover page ---
    doc.add_paragraph("")
    doc.add_paragraph("")
    doc.add_paragraph("")

    cover_title = doc.add_paragraph()
    cover_title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    run = cover_title.add_run(title)
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(0x1B, 0x3A, 0x5C)

    doc.add_paragraph("")

    cover_org = doc.add_paragraph()
    cover_org.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    run = cover_org.add_run(company_name)
    run.font.size = Pt(16)
    run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    doc.add_paragraph("")

    # Metadata table
    meta_items = [
        ("Document Classification", "Company Confidential"),
        ("Version", "1.0"),
        ("Status", "DRAFT -- Requires Review and Approval"),
        ("Generated", datetime.now().strftime("%B %d, %Y")),
        ("Distribution", "Internal / Assessors"),
    ]

    table = doc.add_table(rows=len(meta_items), cols=2)
    table.style = "Light Grid Accent 1"
    for i, (label, value) in enumerate(meta_items):
        table.rows[i].cells[0].text = label
        table.rows[i].cells[1].text = value
        for cell in table.rows[i].cells:
            for paragraph in cell.paragraphs:
                paragraph.style.font.size = Pt(10)

    doc.add_page_break()

    # --- Table of Contents placeholder ---
    doc.add_heading("Table of Contents", level=1)
    doc.add_paragraph(
        "[Update this table of contents after finalizing the document. "
        "In Word: References > Update Table.]"
    )
    doc.add_page_break()

    # --- Sections ---
    # Group sections: top-level and subsections
    top_sections = [s for s in sections if not s.get("parent_id")]
    child_map = {}
    for s in sections:
        pid = s.get("parent_id")
        if pid:
            child_map.setdefault(pid, []).append(s)

    for section in top_sections:
        section_id = section.get("id", "")
        section_title = section.get("title", "Untitled")

        doc.add_heading(section_title, level=1)

        content = section.get("content", "")
        if content:
            _add_content_paragraphs(doc, content)

        # Render subsections
        for child in child_map.get(section_id, []):
            child_title = child.get("title", "")
            if child_title:
                doc.add_heading(child_title, level=2)

            child_content = child.get("content", "")
            if child_content:
                _add_content_paragraphs(doc, child_content)

    # --- Footer: draft notice ---
    doc.add_page_break()
    notice = doc.add_paragraph()
    notice.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    run = notice.add_run(
        "This document was generated by the CMMC Compliance Platform and requires "
        "human review and approval before it can be used as assessment evidence. "
        "Draft documents do not satisfy CMMC final-form evidence requirements."
    )
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    run.italic = True

    # --- Save ---
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_type = doc_type.replace(" ", "_")
    filename = f"{safe_type}_{company_name.replace(' ', '_')}_{timestamp}.docx"
    filepath = os.path.join(output_dir, filename)

    doc.save(filepath)
    print(f"  Saved: {filepath}")

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return filepath, buffer.read()


def _add_content_paragraphs(doc: Document, content: str):
    """Parse content text into Word paragraphs, handling bullets and numbered lists."""
    for para_text in content.split("\n\n"):
        para_text = para_text.strip()
        if not para_text:
            continue
        # Bullet list
        if para_text.startswith("- ") or para_text.startswith("* "):
            for line in para_text.split("\n"):
                line = line.strip()
                if line.startswith("- ") or line.startswith("* "):
                    line = line[2:].strip()
                if line:
                    doc.add_paragraph(line, style="List Bullet")
        # Numbered list
        elif len(para_text) > 2 and para_text[0].isdigit() and para_text[1:3] in (". ", ") "):
            for line in para_text.split("\n"):
                line = line.strip()
                if line and line[0].isdigit():
                    line = line[line.index(" ") + 1:].strip() if " " in line else line
                if line:
                    doc.add_paragraph(line, style="List Number")
        # Regular paragraph
        else:
            doc.add_paragraph(para_text)
